### ISSUE TITLE
Can't run the progame

### ISSUE THREAD

**Issue by martingg88** [VelbazhdSoftwareLLC/Fruit-Machine-Simulator-with-Excel-Interface#1]
I tried to run the following, but nothing come out. any idea? thanks..

./gradlew jarAll

./gradlew run

**Comment by TodorBalabanov** [comment]
It is building perfectly on my machine.

--- --- ---

![Screen 2021-05-07 at 15 02 45](https://user-images.githubusercontent.com/6023003/117446900-724a2c80-af45-11eb-8046-8ea879521a55.png)

--- --- ---

![Screen 2021-05-07 at 15 02 51](https://user-images.githubusercontent.com/6023003/117446930-7c6c2b00-af45-11eb-9602-acb3c4501614.png)

**Comment by TodorBalabanov** [comment]
The command to run the simulation is given in each slot machine math model file.

--- --- ---

![Screen 2021-05-07 at 15 06 27](https://user-images.githubusercontent.com/6023003/117447395-1e8c1300-af46-11eb-98bb-160383718810.png)

--- --- ---

![Screen 2021-05-07 at 15 07 14](https://user-images.githubusercontent.com/6023003/117447408-28ae1180-af46-11eb-9e76-a0caec15e99d.png)
